#region Copyright

// ©2002-2026 idéMobi
// www.idemobi.com

#endregion

#region

using System.Collections.Generic;
using DMBPageBuilder;

#endregion

namespace DMBComponentBuilder
{
    /// <summary>
    ///     Composes visual theme and state classes for a <see cref="CodeBlockBuilder" />.
    /// </summary>
    public sealed class CodeBlockComposer : IIsCssClassComposer
    {
        #region Instance fields and properties

        private bool _compact;
        private bool _highlightDisabled;
        private CodeBlockTheme _theme = CodeBlockTheme.Default;

        #endregion

        #region Instance methods

        /// <summary>
        ///     Enables or disables the compact presentation.
        /// </summary>
        /// <param name="value">A value indicating whether the compact presentation should be applied.</param>
        /// <returns>The current composer instance.</returns>
        public CodeBlockComposer SetCompact(bool value = true)
        {
            _compact = value;
            return this;
        }

        /// <summary>
        ///     Marks syntax highlighting as disabled for the rendered block.
        /// </summary>
        /// <param name="value">A value indicating whether syntax highlighting is disabled.</param>
        /// <returns>The current composer instance.</returns>
        public CodeBlockComposer SetHighlightDisabled(bool value = true)
        {
            _highlightDisabled = value;
            return this;
        }

        /// <summary>
        ///     Sets the visual theme used by the code block.
        /// </summary>
        /// <param name="theme">The theme to apply.</param>
        /// <returns>The current composer instance.</returns>
        public CodeBlockComposer SetTheme(CodeBlockTheme theme)
        {
            _theme = theme;
            return this;
        }

        #region From interface IIsCssClassComposer

        /// <summary>
        ///     Builds the CSS classes generated by this composer.
        /// </summary>
        /// <returns>The ordered list of CSS class names.</returns>
        public IReadOnlyList<string> BuildClasses()
        {
            List<string> classes = new()
            {
                $"dmb-code-block-{_theme.ToString().ToLowerInvariant()}"
            };

            if (_compact)
            {
                classes.Add("dmb-code-block-compact");
            }

            if (_highlightDisabled)
            {
                classes.Add("dmb-code-block-highlight-disabled");
            }

            return classes;
        }

        /// <summary>
        ///     Creates a copy of the current composer state.
        /// </summary>
        /// <returns>A cloned composer preserving the selected options.</returns>
        public IIsCssClassComposer Clone()
        {
            return new CodeBlockComposer()
                .SetTheme(_theme)
                .SetCompact(_compact)
                .SetHighlightDisabled(_highlightDisabled);
        }

        #endregion

        #endregion
    }
}