#region Copyright

// Game-Data-Forge Solution
// Written by CONTART Jean-François & BOULOGNE Quentin
// DMBComponentBuilder.csproj RatingBadgeComposer.cs create at 2026/05/05
// ©2024-2026 idéMobi SARL FRANCE

#endregion

#region

using DMBBootstrapBuilder;
using DMBPageBuilder;

#endregion

namespace DMBComponentBuilder
{
    /// <summary>
    /// Composes the Bootstrap color, cartouche, and size classes for a <see cref="RatingBadgeBuilder"/>.
    /// </summary>
    public sealed class RatingBadgeComposer : IIsCssClassComposer
    {
        private VariantStyle _variant = VariantStyle.Warning;
        private bool _cartouche;
        private RatingBadgeSize _size = RatingBadgeSize.Normal;

        /// <summary>
        /// Sets the Bootstrap variant used to color the stars and optional cartouche.
        /// </summary>
        /// <param name="variant">The visual variant to apply.</param>
        /// <returns>The current composer instance.</returns>
        public RatingBadgeComposer SetVariant(VariantStyle variant)
        {
            _variant = variant;
            return this;
        }

        /// <summary>
        /// Enables or disables the cartouche presentation around the rating.
        /// </summary>
        /// <param name="value">A value indicating whether the cartouche should be rendered.</param>
        /// <returns>The current composer instance.</returns>
        public RatingBadgeComposer SetCartouche(bool value = true)
        {
            _cartouche = value;
            return this;
        }

        /// <summary>
        /// Sets the size preset used by the rating badge.
        /// </summary>
        /// <param name="size">The size preset to apply.</param>
        /// <returns>The current composer instance.</returns>
        public RatingBadgeComposer SetSize(RatingBadgeSize size)
        {
            _size = size;
            return this;
        }

        /// <summary>
        /// Builds the CSS classes generated by this composer.
        /// </summary>
        /// <returns>The ordered list of CSS class names.</returns>
        public IReadOnlyList<string> BuildClasses()
        {
            List<string> classes = new();
            string variant = _variant.GetVariantCss();

            if (!string.IsNullOrWhiteSpace(variant))
            {
                classes.Add($"text-{variant}");
            }

            if (_cartouche)
            {
                classes.Add("rating-badge-cartouche");

                if (!string.IsNullOrWhiteSpace(variant))
                {
                    classes.Add($"rating-badge-cartouche-{variant}");
                }
            }

            switch (_size)
            {
                case RatingBadgeSize.Small:
                    classes.Add("rating-badge-sm");
                    break;

                case RatingBadgeSize.Large:
                    classes.Add("rating-badge-lg");
                    break;
            }

            return classes;
        }

        /// <summary>
        /// Creates a copy of the current composer state.
        /// </summary>
        /// <returns>A cloned composer preserving the selected variant, cartouche, and size.</returns>
        public IIsCssClassComposer Clone()
        {
            return new RatingBadgeComposer()
                .SetVariant(_variant)
                .SetCartouche(_cartouche)
                .SetSize(_size);
        }
    }
}
