#region Copyright

// ©2002-2026 idéMobi
// www.idemobi.com

#endregion

#region

using System.Collections.Generic;
using DMBPageBuilder;

#endregion

namespace DMBComponentBuilder
{
    /// <summary>
    ///     Composes optional animation and hover effect classes for a <see cref="RatingBadgeBuilder" />.
    /// </summary>
    public sealed class RatingBadgeEffectComposer : IIsCssClassComposer
    {
        #region Instance fields and properties

        private bool _hoverGlow;
        private bool _hoverLift;
        private bool _pop;
        private bool _pulse;
        private bool _sparkle;

        #endregion

        #region Instance methods

        /// <summary>
        ///     Enables or disables the hover glow interaction on filled stars.
        /// </summary>
        /// <param name="value">A value indicating whether the hover glow effect should be applied.</param>
        /// <returns>The current composer instance.</returns>
        public RatingBadgeEffectComposer SetHoverGlow(bool value = true)
        {
            _hoverGlow = value;
            return this;
        }

        /// <summary>
        ///     Enables or disables the hover lift interaction on the badge.
        /// </summary>
        /// <param name="value">A value indicating whether the hover lift effect should be applied.</param>
        /// <returns>The current composer instance.</returns>
        public RatingBadgeEffectComposer SetHoverLift(bool value = true)
        {
            _hoverLift = value;
            return this;
        }

        /// <summary>
        ///     Enables or disables the staggered pop-in animation for stars.
        /// </summary>
        /// <param name="value">A value indicating whether the pop effect should be applied.</param>
        /// <returns>The current composer instance.</returns>
        public RatingBadgeEffectComposer SetPop(bool value = true)
        {
            _pop = value;
            return this;
        }

        /// <summary>
        ///     Enables or disables the subtle pulse animation on filled stars.
        /// </summary>
        /// <param name="value">A value indicating whether the pulse effect should be applied.</param>
        /// <returns>The current composer instance.</returns>
        public RatingBadgeEffectComposer SetPulse(bool value = true)
        {
            _pulse = value;
            return this;
        }

        /// <summary>
        ///     Enables or disables the sparkle sweep animation across stars.
        /// </summary>
        /// <param name="value">A value indicating whether the sparkle effect should be applied.</param>
        /// <returns>The current composer instance.</returns>
        public RatingBadgeEffectComposer SetSparkle(bool value = true)
        {
            _sparkle = value;
            return this;
        }

        #region From interface IIsCssClassComposer

        /// <summary>
        ///     Builds the CSS classes generated by this composer.
        /// </summary>
        /// <returns>The ordered list of CSS class names.</returns>
        public IReadOnlyList<string> BuildClasses()
        {
            List<string> classes = new();

            if (_pop)
            {
                classes.Add("rating-badge-effect-pop");
            }

            if (_sparkle)
            {
                classes.Add("rating-badge-effect-sparkle");
            }

            if (_pulse)
            {
                classes.Add("rating-badge-effect-pulse");
            }

            if (_hoverLift)
            {
                classes.Add("rating-badge-effect-hover-lift");
            }

            if (_hoverGlow)
            {
                classes.Add("rating-badge-effect-hover-glow");
            }

            return classes;
        }

        /// <summary>
        ///     Creates a copy of the current effect composer state.
        /// </summary>
        /// <returns>A cloned composer preserving the enabled effects.</returns>
        public IIsCssClassComposer Clone()
        {
            return new RatingBadgeEffectComposer()
                .SetPop(_pop)
                .SetSparkle(_sparkle)
                .SetPulse(_pulse)
                .SetHoverLift(_hoverLift)
                .SetHoverGlow(_hoverGlow);
        }

        #endregion

        #endregion
    }
}